// Product storytelling is kept separate from the legal and support disclosures.
export const homeContent = {
  "zh-Hans": {
    title: "宠物日常，认真记录", description: "用 Petter Days 记录宠物日常，自由定义记录类型，安排照护、管理用品，轻碰 NFC 快速记录。",
    nav: ["特色", "NFC", "支持"], hero: ["它的每一天。", "都值得好好记。"], intro: "从一口水，到一份陪伴。", explore: "看看它能做什么", devices: "在 iPhone 和 iPad 上，照顾好每个小日常。",
    records: { label: "日常记录", title: ["小小日常。", "大有可记。"], tabs: ["丰富的记录类型", "自由定义记录"], captions: ["吃喝、健康、护理，一起记。", "字段、选项、单位，按你的习惯来。"], types: ["饮水", "进食", "体重", "护理", "用药", "自定义"] },
    care: { label: "照护计划", title: ["记得每件事。", "也记得陪伴。"], intro: "一次安排，日复一日的用心。", weekdays: ["一", "二", "三", "四", "五", "六", "日"], rows: ["梳毛", "刷牙", "营养补充"], repeat: "每天", done: "已完成", pending: "待照护" },
    supplies: { label: "用品管理", title: ["它的小仓库。", "心里有数。"], intro: "库存、临期、采购，一眼看清。", tags: ["库存", "临期", "采购"] },
    nfc: { label: "NFC 快速记录", title: ["碰一碰。", "快一点记。"], intro: "把记录入口，放在你顺手的地方。", water: "饮水", note: "需支持 NFC 的 iPhone 与可写入的 NFC 标签。", illustration: "功能示意" },
    ownership: { title: ["陪伴很珍贵。", "记录也一样。"], items: ["离线也能记录", "数据存在本机", "备份，随你带走"] },
    closing: "好好记录，好好陪伴。", download: "App Store 下载", platforms: "适用于 iPhone 和 iPad", demo: "画面使用示例数据；部分配图为功能示意。", medical: "用于宠物照护记录，不能替代兽医诊断。", data: "数据管理", skip: "跳至正文", screenshot: "Petter Days 实际 App 画面", pet: "乔治",
  },
  "zh-Hant": {
    title: "毛孩日常，用心記下", description: "用 Petter Days 記下毛孩日常，自訂紀錄類型、安排照護、管理用品，輕碰 NFC 快速紀錄。",
    nav: ["特色", "NFC", "支援"], hero: ["牠的每一天。", "都值得用心記下。"], intro: "從一口水，到一份陪伴。", explore: "看看它能做什麼", devices: "在 iPhone 和 iPad 上，照顧好每個小日常。",
    records: { label: "日常紀錄", title: ["小小日常。", "大有可記。"], tabs: ["豐富的紀錄類型", "自由自訂紀錄"], captions: ["飲食、健康、日常照護，一起記。", "欄位、選項、單位，照你的習慣來。"], types: ["飲水", "進食", "體重", "照護", "用藥", "自訂"] },
    care: { label: "照護計畫", title: ["記得每件事。", "也記得陪伴。"], intro: "一次安排，每一天的用心。", weekdays: ["一", "二", "三", "四", "五", "六", "日"], rows: ["梳毛", "刷牙", "營養補充"], repeat: "每天", done: "已完成", pending: "待照護" },
    supplies: { label: "用品管理", title: ["牠的小倉庫。", "心裡有數。"], intro: "庫存、到期日、採購，一眼看清。", tags: ["庫存", "即將到期", "採購"] },
    nfc: { label: "NFC 快速紀錄", title: ["碰一下。", "快一點記。"], intro: "把紀錄入口，放在順手的地方。", water: "飲水", note: "需支援 NFC 的 iPhone 與可寫入的 NFC 標籤。", illustration: "功能示意" },
    ownership: { title: ["陪伴很珍貴。", "紀錄也一樣。"], items: ["離線也能紀錄", "資料存在裝置", "備份，隨你帶走"] },
    closing: "用心記錄，用心陪伴。", download: "在 App Store 下載", platforms: "適用於 iPhone 和 iPad", demo: "畫面使用示例資料；部分配圖為功能示意。", medical: "用於寵物照護紀錄，不能取代獸醫診斷。", data: "資料管理", skip: "跳至正文", screenshot: "Petter Days 實際 App 畫面", pet: "乔治",
  },
  "en": {
    title: "A little care, every day", description: "Record your pet’s days with Petter Days. Make records your own, plan care, keep supplies in order, and open a record with an NFC tap.",
    nav: ["Features", "NFC", "Support"], hero: ["Their little days.", "Worth remembering."], intro: "Every sip. Every moment. Every bit of care.", explore: "Take a closer look", devices: "A little care, on iPhone and iPad.",
    records: { label: "Everyday records", title: ["Little moments.", "Lots to record."], tabs: ["More ways to record", "Make it your own"], captions: ["Meals, health, grooming. All together.", "Your fields. Your options. Your way."], types: ["Water", "Meals", "Weight", "Grooming", "Medication", "Custom"] },
    care: { label: "Care plans", title: ["Remember the care.", "Enjoy the company."], intro: "Set the routine. Keep the love going.", weekdays: ["M", "T", "W", "T", "F", "S", "S"], rows: ["Brush coat", "Brush teeth", "Supplement"], repeat: "Daily", done: "Done", pending: "Up next" },
    supplies: { label: "Pet supplies", title: ["Their little cupboard.", "All in hand."], intro: "Stock, expiry dates, purchases. At a glance.", tags: ["Stock", "Expiry", "Purchases"] },
    nfc: { label: "NFC quick records", title: ["A little tap.", "A quicker record."], intro: "Put a shortcut right where you need it.", water: "Water", note: "Requires an NFC-compatible iPhone and a writable NFC tag.", illustration: "Feature illustration" },
    ownership: { title: ["Their days matter.", "So do your records."], items: ["Record offline", "Stored on your device", "Back up and take it with you"] },
    closing: "Good records. Better days together.", download: "Download on the App Store", platforms: "For iPhone and iPad", demo: "Screens show sample data. Some visuals illustrate features.", medical: "A pet care journal. Not a substitute for veterinary diagnosis.", data: "Data choices", skip: "Skip to content", screenshot: "Actual Petter Days app screen", pet: "乔治",
  },
  "ja": {
    title: "ペットとの毎日を、やさしく記録", description: "Petter Days でペットの日常を記録。項目のカスタマイズ、ケアの予定、用品の管理、NFC でのすばやい記録をひとつに。",
    nav: ["特長", "NFC", "サポート"], hero: ["いつもの毎日を。", "大切な記録に。"], intro: "ひと口の水も、一緒に過ごす時間も。", explore: "できることを見る", devices: "iPhone と iPad で、毎日の小さなケアを。",
    records: { label: "日々の記録", title: ["小さな日常。", "記録はたっぷり。"], tabs: ["いろいろな記録", "自分らしくカスタマイズ"], captions: ["食事も、健康も、お手入れも。", "項目、選択肢、単位を、いつものやり方に。"], types: ["水分", "食事", "体重", "お手入れ", "投薬", "カスタム"] },
    care: { label: "ケアプラン", title: ["ケアは忘れず。", "ふれあいはゆっくり。"], intro: "予定を立てて、毎日のケアを習慣に。", weekdays: ["月", "火", "水", "木", "金", "土", "日"], rows: ["ブラッシング", "歯みがき", "栄養補給"], repeat: "毎日", done: "完了", pending: "これから" },
    supplies: { label: "用品管理", title: ["あの子の用品。", "ひと目で把握。"], intro: "在庫も、期限も、購入履歴も。", tags: ["在庫", "期限", "購入"] },
    nfc: { label: "NFC クイック記録", title: ["かざして。", "さっと記録。"], intro: "よく使う場所に、記録の入口を。", water: "水分", note: "NFC 対応 iPhone と書き込み可能な NFC タグが必要です。", illustration: "機能イメージ" },
    ownership: { title: ["大切な毎日。", "大切な記録。"], items: ["オフラインでも記録", "データは端末に保存", "バックアップして持ち出せる"] },
    closing: "記録とともに、もっといい毎日へ。", download: "App Store でダウンロード", platforms: "iPhone と iPad に対応", demo: "画面はサンプルデータです。一部の図は機能イメージです。", medical: "ペットケアの記録ツールです。獣医師の診断に代わるものではありません。", data: "データ管理", skip: "本文へ移動", screenshot: "Petter Days の実際の App 画面", pet: "乔治",
  },
  "ko": {
    title: "반려동물의 하루를 다정하게 기록", description: "Petter Days로 반려동물의 일상을 기록하세요. 기록 항목을 내 방식대로 만들고, 돌봄과 용품을 관리하고, NFC로 빠르게 기록할 수 있어요.",
    nav: ["주요 기능", "NFC", "지원"], hero: ["소중한 하루하루.", "다정하게 기록해요."], intro: "물 한 모금부터, 함께한 순간까지.", explore: "어떤 기능이 있나요?", devices: "iPhone과 iPad에서 이어지는 작은 돌봄.",
    records: { label: "일상 기록", title: ["작은 일상에도.", "기록할 건 많죠."], tabs: ["다양한 기록 종류", "내 방식대로 기록"], captions: ["식사, 건강, 털 관리까지 한곳에.", "항목, 선택지, 단위를 원하는 대로."], types: ["수분", "식사", "체중", "털 관리", "투약", "사용자 지정"] },
    care: { label: "돌봄 계획", title: ["돌봄은 잊지 않고.", "함께하는 시간은 넉넉히."], intro: "한 번 정한 루틴, 매일 이어지는 마음.", weekdays: ["월", "화", "수", "목", "금", "토", "일"], rows: ["빗질", "양치", "영양 보충"], repeat: "매일", done: "완료", pending: "할 일" },
    supplies: { label: "용품 관리", title: ["작은 용품 창고.", "한눈에 알아요."], intro: "재고, 유효기간, 구매 내역을 한곳에서.", tags: ["재고", "유효기간", "구매"] },
    nfc: { label: "NFC 빠른 기록", title: ["가볍게 태그.", "빠르게 기록."], intro: "손이 닿는 곳에 기록 바로가기를 두세요.", water: "수분", note: "NFC 지원 iPhone과 쓰기 가능한 NFC 태그가 필요합니다.", illustration: "기능 예시" },
    ownership: { title: ["소중한 우리 일상.", "기록도 소중하니까."], items: ["오프라인에서도 기록", "기기에 보관하는 데이터", "백업해서 가져가요"] },
    closing: "다정한 기록, 더 좋은 우리 하루.", download: "App Store에서 다운로드", platforms: "iPhone 및 iPad에서 사용", demo: "화면에는 예시 데이터가 사용됩니다. 일부 그림은 기능 예시입니다.", medical: "반려동물 돌봄 기록 도구이며 수의사의 진단을 대신하지 않습니다.", data: "데이터 관리", skip: "본문으로 이동", screenshot: "실제 Petter Days 앱 화면", pet: "乔治",
  },
};
